# Generated by Django 4.0.2 on 2022-05-12 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ammunition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва снаряду')),
                ('caliber', models.CharField(max_length=100, verbose_name='Калібр снаряду')),
                ('type', models.CharField(max_length=100, verbose_name='Тип снаряду')),
                ('appointment', models.CharField(max_length=100, verbose_name='Призначення снаряду')),
                ('range', models.CharField(max_length=100, verbose_name='Дальність польоту снаряду')),
            ],
            options={
                'verbose_name': 'Снаряд',
                'verbose_name_plural': 'Снаряди',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('soldat', models.IntegerField(verbose_name='Кількість солдат тисячі')),
                ('money', models.IntegerField(verbose_name='Витрати на оборону в мільйонах доларів')),
                ('m_vvp', models.FloatField(verbose_name='Витрати на оборону в відсотках ВВП')),
                ('s_1000', models.IntegerField(verbose_name='Кількість солдат на тисячу населення')),
            ],
            options={
                'verbose_name': 'Країна',
                'verbose_name_plural': 'Країни',
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва зброї')),
                ('caliber', models.CharField(max_length=100, verbose_name='Калібр зброї')),
                ('range', models.CharField(max_length=100, verbose_name='Дальність польоту снаряду')),
                ('spm', models.CharField(max_length=100, verbose_name='Скорострільність')),
                ('country', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='movies.country', verbose_name='Країна виробник зброї')),
            ],
            options={
                'verbose_name': 'Ствольна зброя',
                'verbose_name_plural': 'Ствольна зброя',
            },
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Серія корабля')),
                ('displacement', models.CharField(max_length=100, verbose_name='Водотоннажність')),
                ('appointment', models.CharField(max_length=100, verbose_name='Призначення корабля')),
                ('autonomy', models.CharField(max_length=100, verbose_name='Автономність плавання')),
                ('year', models.IntegerField(default=2012, verbose_name='Рік спуску на воду')),
                ('country', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='movies.country', verbose_name='Країна виробник корабля')),
            ],
            options={
                'verbose_name': 'Корабель',
                'verbose_name_plural': 'Кораблі',
            },
        ),
        migrations.CreateModel(
            name='Rocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва ракети')),
                ('height', models.CharField(max_length=100, verbose_name='Висота польту ракети')),
                ('year', models.IntegerField(default=2012, verbose_name='Імя')),
                ('range', models.CharField(max_length=100, verbose_name='Імя')),
                ('country', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='movies.country', verbose_name='Країна виробник ракети')),
            ],
            options={
                'verbose_name': 'Ракета',
                'verbose_name_plural': 'Дакети',
            },
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва літака')),
                ('weapon', models.CharField(max_length=100, verbose_name='Основне озброєння літака')),
                ('appointment', models.CharField(max_length=100, verbose_name='Призначення літака')),
                ('range', models.CharField(max_length=100, verbose_name='Дальність польоту')),
                ('country', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.country', verbose_name='Країна виробник літака')),
            ],
            options={
                'verbose_name': 'Викладач',
                'verbose_name_plural': 'Викладачі',
            },
        ),
        migrations.CreateModel(
            name='OBT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва ОБТ')),
                ('weapon', models.CharField(max_length=100, verbose_name='Основне озброєння ОБТ')),
                ('speed', models.CharField(max_length=100, verbose_name='Швидкість ходу ОБТ')),
                ('range', models.CharField(max_length=100, verbose_name='Запас ходу ОБТ')),
                ('country', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.country', verbose_name='Країна виробник ОБТ')),
            ],
        ),
        migrations.CreateModel(
            name='Artillery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва артилерії')),
                ('range', models.CharField(max_length=100, verbose_name='Імя')),
                ('range_move', models.CharField(max_length=100, verbose_name='Імя')),
                ('spm', models.IntegerField(default=6, verbose_name='Кількість пострілів в хвилину')),
                ('ammunition', models.ManyToManyField(max_length=100, to='movies.Ammunition', verbose_name='Сумісні снаряди')),
                ('country', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.country', verbose_name='Країна виробник артилерії')),
            ],
            options={
                'verbose_name': 'Артилерія',
                'verbose_name_plural': 'Артилерія',
            },
        ),
    ]
