# Generated by Django 4.0.2 on 2022-05-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='model',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
