# Generated by Django 4.0.2 on 2022-05-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_request_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artillery',
            name='ammunition',
        ),
        migrations.AddField(
            model_name='artillery',
            name='ammunition',
            field=models.CharField(max_length=100, null=True, verbose_name='Сумісні снаряди'),
        ),
        migrations.AlterField(
            model_name='artillery',
            name='country',
            field=models.CharField(max_length=100, null=True, verbose_name='Країна виробник артилерії'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='obt',
            name='country',
            field=models.CharField(max_length=100, null=True, verbose_name='Країна виробник ОБТ'),
        ),
        migrations.AlterField(
            model_name='plane',
            name='country',
            field=models.CharField(max_length=100, null=True, verbose_name='Країна виробник літака'),
        ),
        migrations.AlterField(
            model_name='rocket',
            name='country',
            field=models.CharField(max_length=100, null=True, verbose_name='Країна виробник ракети'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='country',
            field=models.CharField(max_length=100, null=True, verbose_name='Країна виробник корабля'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='country',
            field=models.CharField(max_length=100, null=True, verbose_name='Країна виробник зброї'),
        ),
    ]
