# Generated by Django 4.0.2 on 2022-05-14 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_artillery_ammunition_artillery_ammunition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artillery',
            name='ammunition',
        ),
        migrations.AddField(
            model_name='artillery',
            name='ammunition',
            field=models.ManyToManyField(max_length=100, null=True, to='movies.Ammunition', verbose_name='Сумісні снаряди'),
        ),
        migrations.AlterField(
            model_name='artillery',
            name='country',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.country', verbose_name='Країна виробник артилерії'),
        ),
        migrations.AlterField(
            model_name='obt',
            name='country',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.country', verbose_name='Країна виробник ОБТ'),
        ),
        migrations.AlterField(
            model_name='plane',
            name='country',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.country', verbose_name='Країна виробник літака'),
        ),
        migrations.AlterField(
            model_name='rocket',
            name='country',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.country', verbose_name='Країна виробник ракети'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='country',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.country', verbose_name='Країна виробник корабля'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='country',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.country', verbose_name='Країна виробник зброї'),
        ),
    ]
