# Generated by Django 4.0.2 on 2022-05-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_artillery_ammunition_artillery_ammunition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='weapon',
            field=models.CharField(max_length=100, null=True, verbose_name='Основне озброєння літака'),
        ),
    ]
