# Generated by Django 4.0.2 on 2022-05-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_plane_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='speed',
            field=models.CharField(max_length=100, null=True, verbose_name='Швидкість польоту ракети'),
        ),
        migrations.AlterField(
            model_name='rocket',
            name='range',
            field=models.CharField(max_length=100, verbose_name='Глибина ураження'),
        ),
        migrations.AlterField(
            model_name='rocket',
            name='year',
            field=models.IntegerField(default=2012, verbose_name='Рік поставки на озброєння'),
        ),
    ]
