# Generated by Django 4.0.2 on 2022-05-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_weapon_speed_alter_rocket_range_alter_rocket_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='speed',
        ),
        migrations.AddField(
            model_name='rocket',
            name='speed',
            field=models.CharField(max_length=100, null=True, verbose_name='Швидкість польоту ракети'),
        ),
    ]
